### ISSUE TITLE
IllegalArgumentException for trying to unregister an observer that is not registered?

### ISSUE THREAD

**Issue by ghost** [benknoble/Comp401-A7#1]
In your test your seeing if unregisterROIObserver() throws an IllegalArgumentException if it's called with an observer parameter that isn't registered. Why? That's not a requirement as listed in the assignment. Would it be better to simply not do anything? 

`try {
	    p.unregisterROIObserver(obsB);
	    fail("didn't throw for unregistration of observer not registered");
	} catch (IllegalArgumentException e) {
	}`

**Comment by benknoble** [comment]
That was a detail I decided on because I couldn't come up with a real use-case in which you would actually try to detach an observer not already attached. On further reflection (i.e. after playing with Java's ArrayList), it seems that e.g. List does not throw an exception when you remove an element not in the list. This needs to be changed
